ARG BASE_IMAGE=glukw/openclaw-vnc-base:latest
FROM ${BASE_IMAGE}

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      chromium chromium-sandbox && \
    rm -rf /var/lib/apt/lists/* && \
    chmod 4755 /usr/lib/chromium/chrome-sandbox
